services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql8
    environment:
      - 'MYSQL_DATABASE=audio_service_db'
      - 'MYSQL_PASSWORD=audio_pass'
      - 'MYSQL_ROOT_PASSWORD=audio_root_pass'
      - 'MYSQL_USER=audio_svc'
    ports:
      - '3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data: